// engine_luauembed -- compiles the builtins written in Luau into bytecode the
// script module embeds (ADR 0094).
//
//   engine_luauembed <output.cpp> <Global>=<file.luau> [<Global>=<file.luau> ...]
//
// The shipping profile carries no compiler (ADR 0002), so a builtin shipped as
// source could not run there. Compiling it here, with the options the runtime
// compiles every script with (`compile_options.h`), gives every profile the
// same bytecode -- and the order of the arguments is the order they install.
//
// A host tool, built for the machine the build runs on. It lives inside the
// script module because this is the one module allowed to include a Luau
// header.

#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "engine/script/compile_options.h"

namespace {

struct Builtin
{
    std::string global;
    std::string path;
    std::string bytecode;
};

[[nodiscard]] bool readFile(const std::string& path, std::string& out)
{
    std::ifstream file(path, std::ios::binary);
    if (!file)
        return false;
    std::ostringstream text;
    text << file.rdbuf();
    out = text.str();
    return true;
}

} // namespace

int main(int argc, char** argv)
{
    if (argc < 3) {
        std::fprintf(stderr, "usage: engine_luauembed <output.cpp> <Global>=<file.luau> ...\n");
        return 2;
    }

    std::vector<Builtin> builtins;
    for (int index = 2; index < argc; ++index) {
        const std::string argument = argv[index];
        const std::size_t equals = argument.find('=');
        if (equals == std::string::npos || equals == 0) {
            std::fprintf(stderr, "engine_luauembed: '%s' is not <Global>=<file.luau>\n", argument.c_str());
            return 2;
        }
        Builtin builtin{argument.substr(0, equals), argument.substr(equals + 1), {}};
        std::string source;
        if (!readFile(builtin.path, source)) {
            std::fprintf(stderr, "engine_luauembed: cannot read %s\n", builtin.path.c_str());
            return 1;
        }

        lua_CompileOptions options{};
        engine::script::configureCompileOptions(options);
        std::size_t size = 0;
        char* bytecode = luau_compile(source.data(), source.size(), &options, &size);
        if (bytecode == nullptr) {
            std::fprintf(stderr, "engine_luauembed: %s produced no bytecode\n", builtin.path.c_str());
            return 1;
        }
        builtin.bytecode.assign(bytecode, size);
        std::free(bytecode);
        // A compile error is bytecode too: a zero version byte, then the
        // message. It is a build error here, not a runtime one in a game.
        if (!builtin.bytecode.empty() && builtin.bytecode[0] == 0) {
            std::fprintf(stderr, "%s:%s\n", builtin.path.c_str(), builtin.bytecode.c_str() + 1);
            return 1;
        }
        builtins.push_back(std::move(builtin));
    }

    std::ostringstream out;
    out << "// Generated by engine_luauembed from runtime/builtins (ADR 0094). Do not edit.\n";
    out << "#include \"engine/script/builtins.h\"\n\n";
    out << "namespace engine::script {\nnamespace {\n\n";
    for (std::size_t at = 0; at < builtins.size(); ++at) {
        out << "constexpr unsigned char kBytecode" << at << "[] = {";
        const std::string& bytes = builtins[at].bytecode;
        for (std::size_t byte = 0; byte < bytes.size(); ++byte) {
            if (byte % 20 == 0)
                out << "\n   ";
            out << ' ' << static_cast<unsigned>(static_cast<unsigned char>(bytes[byte])) << ',';
        }
        out << "\n};\n\n";
    }
    out << "constexpr BuiltinChunk kBuiltins[] = {\n";
    for (std::size_t at = 0; at < builtins.size(); ++at)
        out << "    {\"" << builtins[at].global << "\", kBytecode" << at << ", sizeof(kBytecode" << at << ")},\n";
    out << "};\n\n} // namespace\n\n";
    out << "std::span<const BuiltinChunk> builtinChunks() noexcept\n{\n    return kBuiltins;\n}\n\n";
    out << "} // namespace engine::script\n";

    // Written every time it runs: the build runs it only when a builtin or the
    // tool changed, and an output left untouched would look stale to it.
    std::ofstream file(argv[1], std::ios::binary | std::ios::trunc);
    file << out.str();
    return file ? 0 : 1;
}
