# The flags Luau's type checker defines, as a header the script editor's checker
# turns on (ADR 0093, amended 2026-10-06).
#
# **Why a generated list.** Luau ships every change to its checker behind a
# flag that is off until the change has been through its own release train,
# and its own tools -- `luau-analyze`, and the `luau-lsp` that `ludwerk check`
# runs -- turn them all on (`setLuauFlagsDefault`, less the few
# `isAnalysisFlagExperimental` names). The editor's checker ran with none on:
# the new solver at the pin with every fix made since it was written switched
# off, which reported `hero.Body.Parent` on a value typed `any` as "type
# 'unknown' does not have key 'Parent'" in a project `ludwerk check` called
# clean.
#
# **And why only the checker's.** A flag is process-wide and found by name, and
# the same list holds the parser's, the compiler's and the VM's -- turning
# those on in the editor would run a game there on a different VM from the one
# it ships with (R10). A flag DEFINED under `Analysis/` or `EqSat/` cannot be
# read by the VM, the compiler or the parser: those libraries are built and
# linked without the checker (a shipped game carries none, ADR 0002), so a
# reference from them would not link. The definitions are read from the
# vendored sources at the pin, so the list moves with the pin and nobody
# keeps it.

function(engine_luau_analysis_flags output)
    file(GLOB sources CONFIGURE_DEPENDS
        "${CMAKE_SOURCE_DIR}/third_party/luau/Analysis/src/*.cpp"
        "${CMAKE_SOURCE_DIR}/third_party/luau/EqSat/src/*.cpp")
    set(names "")
    foreach(source IN LISTS sources)
        file(STRINGS "${source}" lines REGEX "^LUAU_(DYNAMIC_)?FASTFLAGVARIABLE\\(Luau[A-Za-z0-9_]+")
        foreach(line IN LISTS lines)
            string(REGEX REPLACE "^LUAU_(DYNAMIC_)?FASTFLAGVARIABLE\\((Luau[A-Za-z0-9_]+).*$" "\\2" name "${line}")
            list(APPEND names "${name}")
        endforeach()
    endforeach()
    list(REMOVE_DUPLICATES names)
    list(SORT names)
    list(LENGTH names count)
    if(count EQUAL 0)
        message(FATAL_ERROR
            "No checker flag was found under third_party/luau/Analysis/src: the macro that defines one changed its "
            "spelling, and cmake/engine_luau_analysis_flags.cmake must read the new one.")
    endif()

    set(text "// Generated by cmake/engine_luau_analysis_flags.cmake from the vendored Luau. Not edited.\n")
    string(APPEND text "#pragma once\n\n#include <string_view>\n\nnamespace engine::app {\n\n")
    string(APPEND text "inline constexpr std::string_view LuauAnalysisFlags[] = {\n")
    foreach(name IN LISTS names)
        string(APPEND text "    \"${name}\",\n")
    endforeach()
    string(APPEND text "};\n\n} // namespace engine::app\n")
    file(CONFIGURE OUTPUT "${output}" CONTENT "${text}" @ONLY)
endfunction()
