# A full material permutation is not the compact Fast/Flat layout. Check the
# actual draw commands, rather than just shader metadata or variant selection.
execute_process(
    COMMAND "${HOST}" "${SCENARIO}" --headless --frames=3 --exit --rhi=capture "--capture-out=${OUTPUT}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE output)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Terrain capture failed: ${output}")
endif()
file(STRINGS "${OUTPUT}" lines)
set(terrain_pipeline "")
set(selected FALSE)
set(textures 0)
set(draws 0)
foreach(line IN LISTS lines)
    string(JSON op GET "${line}" op)
    if(op STREQUAL "createGraphicsPipeline")
        string(JSON name GET "${line}" name)
        if(name STREQUAL "terrain_triplanar_no_hex")
            string(JSON terrain_pipeline GET "${line}" pipeline)
        endif()
    elseif(op STREQUAL "setPipeline")
        string(JSON pipeline GET "${line}" pipeline)
        set(selected FALSE)
        set(textures 0)
        if(NOT terrain_pipeline STREQUAL "" AND pipeline STREQUAL terrain_pipeline)
            set(selected TRUE)
        endif()
    elseif(selected AND op STREQUAL "bindTextures")
        string(JSON textures GET "${line}" count)
    elseif(selected AND op STREQUAL "drawIndexed")
        if(NOT textures EQUAL 16)
            message(FATAL_ERROR "Full terrain draw bound ${textures} textures; expected all sixteen.")
        endif()
        math(EXPR draws "${draws} + 1")
    endif()
endforeach()
if(draws EQUAL 0)
    message(FATAL_ERROR "No full-quality terrain permutation was drawn; the test exercised nothing.")
endif()
message(STATUS "Verified complete texture bindings for ${draws} terrain draws.")
